@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
'!NEW_C4_STYLE=1
'LAYOUT_LANDSCAPE()

Person(user, "Пользователь", "Публикует посты, загружает медиа, просматривает ленты постов, профили и списки пользователей, подписывается на других пользователей, оставляет реакции и комментарии на посты, ищет места для путешествий")

System(4travelers, "Travelers Journal", "Социальная сеть для путешественников: публикация постов, просмотр ленты постов, просмотр профилей и списков пользователей, подписки на пользователей, реакции и комментарии на посты, поиск популярных мест путешествий")
System_Ext(cdn,  "CDN", "Раздача медиа пользователям")

Rel(user, 4travelers, "Читает и создает контент", "HTTPS")
Rel(user, cdn, "Читает медиа", "HTTPS")
Rel(4travelers, cdn, "Загружает медиа", "HTTPS")

SHOW_LEGEND()
@enduml
